### ISSUE TITLE
std.log output goes into the debug console instead of the REPL

### ISSUE THREAD

**Issue by healeycodes** [thesephist/maverick#1] opened 2021-06-05 06:05 UTC
This might be expected behavior? Just checking.

## Reproduce

```
log(1)
```
Prints to REPL

```
log := std.log
log(1)
```

Prints to console and _not_ the REPL

**Comment by thesephist** [comment] 2021-06-09 06:37
It's... expected behavior, haha. It's a weird quirk of the fact that the REPL and the rest of the app run in the same top level environment/scope, so in the REPL `log` and `out` are re-declared to log to the REPL [here](https://github.com/thesephist/maverick/blob/main/src/app.js.ink#L65), but the global `std.log` is not overridden because that would be mutating this big global variable instead of adding a local variable to this local scope.

It's probably possible to swap out `std.log` during the REPL execution and swap it back or something, but i haven't found it too annoying or problematic yet so I haven't fixed it.

**Comment by thesephist** [comment] 2021-06-09 06:40
Going to close for now as a wontfix for reasons above :) but might rethink this later. I'm not super set on it.

**Closed as completed by thesephist** 2021-06-09 06:40 UTC
Labels: wontfix
